Feature/net 468 object counter in category sidebar
NETHINKS/DATAGERRY pull request #94
Opened 2020-10-21 13:18 UTC by doblanken

Updates the object counter in the category sidebar when objects are added or deleted.
Resolves the issue stated in [NET-468](https://nethinks.atlassian.net/browse/NET-468)

2020-10-21 14:02 UTC, markheumueller requested changes
Hey Dorus, please look again with TSLint over it. I get several errors displayed there.

2020-10-21 14:02 UTC, markheumueller commented on app/src/app/layout/services/sidebar.service.ts
> +    sidebarType.objectCounter = await this.getObjectCount(sidebarType.type.public_id);
You store a promise in a number field here.

2020-10-21 14:15 UTC, doblanken commented
> Hey Dorus, please look again with TSLint over it. I get several errors displayed there.

Could you please define which errors are displayed? I don't see any here.

2020-10-22 07:50 UTC, markheumueller approved these changes
LGTM

2020-10-22 07:58 UTC, merged